apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airports-app.fullname" . }}
  labels:
{{ include "airports-app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "airports-app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "airports-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
