apiVersion: v1
kind: Service
metadata:
  name: {{ include "airports-app.fullname" . }}
  labels:
{{ include "airports-app.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "airports-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
