# Default values for airports-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: moustafa3issa/countries-app
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  internalPort: 8080


