apiVersion: v1
kind: Service
metadata:
  name: {{ include "countries-app.fullname" . }}
  labels:
{{ include "countries-app.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort:  {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "countries-app.name" . }}
