apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: airports
spec:
  replicas: 4
  selector:
    matchLabels:
      app: airports
  template:
    metadata:
      labels:
        app: airports
    spec:
      containers:
      - name: airports
        image: airports-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
